version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  assignees:
    - gavlyukovskiy
  groups:
    java-minor:
      update-types:
        - minor
        - patch
  open-pull-requests-limit: 10
